blank_issues_enabled: false
contact_links:
  - name: 技術的な内容以外のご要望・ご提案
    url: https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/covid19_qa_kanrenkigyou_00009.html
    about: 技術的な内容以外のご要望については、本リポジトリでは扱いません。Q&Aページに記載がありますお問い合わせメールアドレスにご連絡いただきますようお願い致します。