name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: CI/PR triggers should be set in the Classic Editor

variables:
- group: app-settings-qa
- group: ios-signing-development
- group: android-signing-dev
- template: templates/variables/app-variables.yml

- script: |
    dotnet --list-sdks
  displayName: dotnet --list-sdks

- script: |
    dotnet --list-runtimes
  displayName: dotnet --list-runtimes

- script: |
    dotnet --info
  displayName: dotnet --info

jobs:
- job: build_ios
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: ios-signing-development
  - template: templates/variables/ios-build-environment-variables.yml
  steps:
  - template: templates/build/ios-build-uitest-template.yml
    parameters:
      isDefineDebug: true

- job: build_android
  pool:
    vmImage: 'macOS-11'
  variables:
  - group: android-signing-dev
  - template: templates/variables/android-build-environment-variables.yml
  steps:
  - template: templates/build/android-build-uitest-template.yml