name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# NOTE: CI/PR triggers should be set in the Classic Editor

variables:
- group: app-settings-prod
- group: ios-signing-distribution
- group: android-signing-prod
- template: templates/variables/app-variables.yml
- template: templates/variables/app-build-variables.yml

jobs:
- job: build_ios
  pool:
    vmImage: '$(IosAppBuildAgent)'
  variables:
  - template: templates/variables/ios-build-environment-variables.yml
  steps:
  - template: templates/build/ios-build-appstore-template.yml

- job: build_android
  pool:
    vmImage: '$(AndroidAppBuildAgent)'
  variables:
  - template: templates/variables/android-build-environment-variables.yml
  steps:
  - template: templates/build/android-build-store-template.yml
