# This is a basic workflow to help you get started with Actions

name: CI-Server

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main, develop, 'feature/**' ]
    paths:
      - '.github/workflows/CIserver.yml'
      - 'src/**'
      - 'Covid19Radar.Functions.sln'
      - 'Covid19Radar.Functions.runsettings'
      - 'Nuget.config'
  pull_request:
    branches: [ main, develop, 'feature/**' ]
    paths:
      - '.github/workflows/CIserver.yml'
      - 'src/**'
      - 'Covid19Radar.Functions.sln'
      - 'Covid19Radar.Functions.runsettings'
      - 'Nuget.config'
jobs:
  build:
    name: build
    runs-on: windows-latest
    strategy:
      matrix:
        Configuration: [Debug, Release]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: install report generator
      run: dotnet tool update dotnet-reportgenerator-globaltool -g
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1
    - name: msbuild
      run: msbuild ${{ github.workspace }}/Covid19Radar.Functions.sln /restore /t:Build /p:Configuration=${{ matrix.Configuration }}
    - name: Execute Unit Tests
      run: dotnet test ${{ github.workspace }}/Covid19Radar.Functions.sln /p:CollectCoverage=true --no-build --logger trx --settings ${{ github.workspace }}/Covid19Radar.Functions.runsettings --collect:"XPlat Code Coverage"     
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true 
    - name: Generate Coverage Report
      run: reportgenerator "-reports:${{ github.workspace }}/TestResults/*/coverage.cobertura.xml" "-targetdir:sonarqubecoverage" "-reporttypes:SonarQube"
