name: Hugo-Site

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'documents/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.87.0'
          extended: true
      - name: Build Site
        run: |
          cd ${{ github.workspace }}/documents
          hugo --minify
          ls ${{ github.workspace }}/documents
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ github.workspace }}/documents/public
          CLEAN: true  
